---
# Configures the firewall by directly motifying IPTables

- name: IPTABLES | 1.0 | Ensure a backup of existing IPtables rules exists
  ansible.builtin.shell: 'iptables-save > {{ firewall.iptables_backup }}'
  changed_when: false
  when: firewall.iptables_backup is defined and firewall.iptables_backup |length > 0

- name: IPTABLES | 2.0 | Ensure the LOGGING chain exists
  shell: iptables --new-chain LOGGING
  changed_when: false
  failed_when: false

- name: IPTABLES | 3.0 | Ensure IPTables packet logging is configured
  ansible.builtin.iptables:
    chain: LOGGING
    action: append
    state: present
    limit: 2/second
    limit_burst: 20
    log_prefix: "IPTABLES:INFO: "
    log_level: info

- name: IPTABLES | 4.0 | Ensure XRDP port is open for connectivity
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    policy: ACCEPT
    protocol: '{{ item }}'
    destination_port: '{{ xrdp.port }}'
  loop:
    - tcp
    - udp

- name: IPTABLES | 5.0 | Ensure SSH access remails after XRDP installation
  ansible.builtin.iptables:
    state: present
    chain: INPUT
    policy: ACCEPT
    protocol: tcp
    destination_port: '{{ firewall.ssh_port }}'
  when: firewall.ssh and firewall.ssh_port is defined