---
# Steps to configure Ubuntu machine to use OpenVPN service with config (headless/daemon mode)

- name: Create a backup of the original openvpn.service file (if not exists)
  copy:
    src: /lib/systemd/system/openvpn.service
    dest: /lib/systemd/system/openvpn.service.bak
    force: false

- name: Template openvpn.service for headless mode
  template:
    src: "{{ role_path }}/templates/openvpn.service.j2"
    dest: /lib/systemd/system/openvpn.service
    force: true

- name: Enable the service on startup
  systemd:
    name: openvpn
    enabled: true

- name: Start the openvpn service
  systemd:
    name: openvpn
    state: started