---
# Install + Configure XRDP on Ubuntu 20.04+

- name: UBUNTU | 1.0 | Make sure all packages sources are up-to-date
  ansible.builtin.apt:
    name: '*'
    state: latest

- name: UBUNTU | 2.0 | Install the ubuntu desktop environment
  ansible.builtin.apt:
    name: "ubuntu-desktop"
    state: present
  when: xrdp.environment == "gnome"

- name: UBUNTU | 3.0 | Install the XFCE ubuntu desktop environment
  ansible.builtin.apt:
    name: "xubuntu-desktop"
    state: present
  when: xrdp.environment == "xfce"

- name: UBUNTU | 4.0 | Initiate configuration of XRDP server
  ansible.builtin.include_tasks: "xrdp.yml"
  notify: Restart XRDP

- name: UBUNTU | 4.0 | Include firewall config
  ansible.builtin.include_tasks: "firewall.yml"
  when: firewall.enabled