---
# handlers file for ansible-xrdp-ubuntu

- name: Restart XRDP
  ansible.builtin.systemd:
    name: xrdp
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: enabled

- name: Restart IPTables
  ansible.builtin.shell: |
    /etc/init.d/network-manager restart
  changed_when: false