---
# handlers file for ansible-xrdp-ubuntu

- name: Reload UFW
  community.general.ufw:
    state: enabled

- name: Restart IPTables
  ansible.builtin.shell: |
    /etc/init.d/iptables restart  
    /etc/init.d/networking restart  
    /etc/init.d/firewall restart
  changed_when: false