---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "3 2 * * 0"

jobs:
  lint:
    name: Lint Ansible
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install lint dependencies
        run: pip3 install yamllint ansible-base ansible-lint
      - name: Lint ansible project
        run: |
          yamllint .
          ansible-lint